### ISSUE TITLE
Type error for returning nested array

### ISSUE THREAD

**Issue by julienvincent** [facebook/dataloader#118]
For some context, I am batching queries that return collections and not individual entities. This means my DataLoader `batchLoadFn` returns an array of arrays.

Functionally this works fine, however Flowtype doesn't like this and spits out the following error: 

```bash
core.js:682
  Member 2:
   67:     return groupByDatatype(datatype_ids, data_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `T` of async return
  Error:
   13: type BatchLoadFn<K, V> = (keys: Array<K>) => Promise<Array<V | Error>>;
                                                                      ^^^^^ Error. This type is incompatible with. See: node_modules/dataloader/index.js.flow:13
   22: ) => Array<Array<UnitDataValue>>
                  ^^^^^^^^^^^^^^^^^^^^ array type
```

If I alter the `batchLoadFn` type definition by removing the `Error` union, everything works fine:

```js
type BatchLoadFn<K, V> = (keys: Array<K>) => Promise<Array<V>>;
```

I am not entirely sure why flow can't associate `Array< UnitDataValue>` to `V` while unioned with `Error` - perhaps this is a bug with flow? Can we change this type definition somehow to allow for arbitrary `V` types?

**Comment by dolphin278** [comment]
It looks like root cause isn't about array nesting – I have same issue for flat arrays – it's something about `BatchLoadFn<K, V>` declaration. On one hand, Flow requires, that BatchLoadFn must return `Promise<Array<V | Error>>`, but if you return such type, it argues, that `Error` is incompatible with V from Dataloaders<K,V>  declaration. This  definitely was not an issue in old Flow versions (around 0.52, 0.46 for sure), but with 0.60.1 it definitely broken.

**Comment by hendrikniemann** [comment]
I was able to reproduce this using an interface [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBCAhugMYAWAMnEQCYBiAdgDwDSANGAGoB8YAvGAAUAa1yYAzgC4wrANoBdAJQC+ABQBOcALYBLCbmYBBDRqKZmXMAB8wAUVNwNPHgG5UqWrlIwiG-D5EEhJgACIkRPB0uBpsnLxgAN6oYGCkcIwS6BoArqToTkIARiQU1HRMMsRkVDQMLBzcPEoy4eiRdTFxTagAvh66jOgxUESk+ADquujkAJKhzAAqfMmpurQyi+x9Hl6B-mAAbn5HkTm40mBTM-PMWRqDAOY8iu6o6ZnoYCU1TAJgQUwjFIwnWl3uT0UKn4PBSqTAYIAdNoiNghOtVEk4fC0hksmAoLpcDBaP9jjBzhJEYTGLQhOTMeTERj+KyEbQlO4cWsoMIAISE4kcrHc+H+dA5DSMMCMXBIBxaDRCAAGABJEutejK4F8oHAcrS+crOdj4f1ReLJdLBST3ABIXom1DFUrkSqEV3lep3bJPTjXOYLCGMZ7NN4u36MKqeupMH0PEP+6aB+NPPi2BVOMMeD74qJeDStCL5rrBx5Jm5B30hlz-WVINodaJKn4UJhKVBAA). The becomes an issue starting at Flow 0.54.0. This seems to be due to wrong type inference. The `batchFn` seems to satisfy both types:

```js
(batchFn: BatchLoadFn<string, WithID<string>>);

(batchFn: BatchLoadFn<string, WithID<string> | Error>);
```

But the constructor call afterwards picks up the wrong type definition. [When I manually add the type to the function](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBCAhugMYAWAMnEQCYBiAdgDwDSANGAGoB8YAvGAAUAa1yYAzgC4wrANoBdAJQC+ABQBOcALYBLCbmYBBDRqKZmXMAB8wAUVNwNPHgG5UqWrlIwiG-D5EEhJgACIkRPB0uBpsnLxgAN6oYGCkcIwS6BoArqToTkIARiQU1HRMMsRkVDQMLBzcPEoy4eiRdTFxTagAvh66jOgxUESk+ADquujkAJKhzAAqfMmpurQyi+x9Hl6B-mAAbn5HkTm40mBTM-PMWRqDAOY8iu6o6ZnoYCU1lYSltQqLHuT041zmCxBjGefEEQUwjFIwnWlyhj0UKn4PBSqTAKIAdNoiNghOtVEkcbi0hksmAoLpcDBaAJTjBzhJ8fTGLQhMcYOS+fiyfwRXjaEp3FS1lBhABCemM8UUqW4-zoHIaRhgRi4JAOLQaIQAAwAJIl1r1tXAvlA4DlubKjRLKbj+iq1RqtQqme4AJC9Z3vGlfKJeDStCKhrposHTCF3bJPFwsnVINodaKGn4UJhKVBAA) the error disappears.

**Comment by leebyron** [comment]
I believe this is due to type invariance on Array types - essentially the `Array<V>` and `Array<V | Error>` are incompatible since Arrays are mutable. If you replace `Array` with `$ReadOnlyArray` then the flow error goes away - this is because a $ReadOnlyArray cannot be mutated and thus is covariant instead of invariant.

I'll look into how I might improve the library flow types to reduce how common this flow error is.

**Comment by leebyron** [comment]
This was fixed in https://github.com/facebook/dataloader/commit/f0291465d37caca07c613222b98e0361a5e5a6cb - but that commit is after the last release, I'll get a new release out soon
