### ISSUE TITLE
Export flow types (Options, CacheMap, and BatchLoadFn)

### ISSUE THREAD

**Issue by erydo** [facebook/dataloader#124]
The type definitions are helpful, but because they're not exported, it makes them difficult to use in composed APIs.

The only real change request here is to add `export` to those type definitions.

**Comment by erictt** [comment]
If you are using flowtype, it probably will warn you when your CacheMap Class doesn't work.

**Comment by erydo** [comment]
My suggestion here isn't about lack of type checking, only that you can't reference those unexported types in your own declarations. Like:
```ts
import DataLoader from 'dataloader';

export default class MyDataLoader extends DataLoader<string, MyType> {
  constructor(someArg: string, options: /* what type declaration to put here? */) {
    super(someBatchLoadFn, options);
  }

  someHelperMethod(): void {
  }
}
```

If they were imported, then one could just:
```ts
import type {Options as DataLoaderOptions} from 'dataloader';
```

**Comment by Togrias** [comment]
Also, Flow seems to type-check incorrectly if you simply define:
`type BatchLoadFn<K,V> = $ReadOnlyArray<K> => Promise<$ReadOnlyArray<V | Error>>`

Somehow, Flow can't resolve (V | Error) properly. So new DataLoader(fn: BatchLoadFn) shows a warning.

The problem goes away if you modify the latest git commit to export the flow types and depend on those exported flow types.

But that seems like a bug with Flow rather than this.
