### ISSUE TITLE
Suggestion: Cache TTL

### ISSUE THREAD

**Issue by dhruvp** [facebook/dataloader#13]
I absolutely love DataLoader so far. One thing that would make it even better is if there were a way to specify a TTL. It could be as simple as running a setTimeout with a call to clear inside it at the ttl. Would this be possible? And I'm happy to help contribute to this too!

**Comment by leebyron** [comment]
Variants of this idea have popped up a number of times. I think the right answer is to allow for the cache implementation itself to be swapped out so that anyone can provide their own, as there are so so many variants on this theme and Dataloader is probably not the best place for a best-of-class cache layer to be written :)

**Comment by leebyron** [comment]
DataLoader can now accept arbitrary cache implementations, which means you can employ whatever cache strategy your heart desires!
