### ISSUE TITLE
Proposal: Batching requests in an interval of time

### ISSUE THREAD

**Issue by davazp** [facebook/dataloader#58]
I would like to propose considering a `interval` option to dataloaders.

This option would allow to batch together requests spanning multiple ticks of the event loop.

A value of 0 (the default) would mean to batch only requests in the same tick, that is, the current behaviour.

It is useful when you have many requests close enough but not exactly in the same tick, and a small latency for individual requests is okay. For example, [apollo-client](https://github.com/apollostack/apollo-client) library supports this approach to batch graphql queries in a window of, by default, 10ms.

**Comment by ericclemmons** [comment]
I can work on a PR if the behavior is OK.  I just ran into a situation where this would be desirable as well.

**Comment by leebyron** [comment]
DataLoader intentionally does not support this because it introduces a floor of latency to all loads which can quickly and unintuitively add up to very slow performance.

Apollo client uses a delayed approach because it is used in an environment where it is common for load operations to be spread across many frames in a short window of time and for ticks to occur very often (~60fps clientS), and the data they are loading (graphql queries) are not interdependent.

In contrast DataLoader is used in environments (servers) where load operations happen in bursts, where ticks only occur when scheduled, and are very often dependent on other load operations which results in the adding up of latency.

**Comment by leebyron** [comment]
I would consider a PR which added this, but I think it definitely needs real numbers to prove that it would improve performance and not hurt performance, both to warrant adding the feature and as future guidance of how others should use it.

**Comment by ericclemmons** [comment]
@leebyron I have a query-heavy (hence DataLoader-heavy) part of my app I can try this on, but I could really use a hint as to _where_ I can swap out the logic & come back with some **real metrics**.

**Comment by leebyron** [comment]
Sure. `enqueuePostPromiseJob` (https://github.com/facebook/dataloader/blob/master/src/index.js#L208) is what is responsible for scheduling work at the end of the promise queue for the current tick. If you replaced the Promise-queue mechanisms with something like `setTimeout` you would get the time-based rather than tick-based behavior.

**Comment by bman654** [comment]
If you add this, I recommend not making it _time_-based, but instead make it _signal_-based.  Something like:

```es6
// mimic current behavior
new DataLoader(batchLoadFn, { batchSignal: () => Promise.resolve() });

// time-based batch
new DataLoader(batchLoadFn, { batchSignal: () => Promise.delay(10) });

// signal-based
new DataLoader(batchLoadFn, { batchSignal: () => waitForSomeSignalToArrive() });

// only wait 10ms for the first batch.
// Subsequent batches wait just one tick (to prevent cascading delays)
const batchSignal = Promise.delay(10);
new DataLoader(batchLoadFn, { batchSignal: () => batchSignal });
```

Effectively this would make the batching strategy injectable.

**Comment by gajus** [comment]
> In contrast DataLoader is used in environments (servers) where load operations happen in bursts, where ticks only occur when scheduled

Any suggestions how to trace down whats forcing a tick to happen?

I have this query:

```graphql
{
  movies(date: "2017-04-06", coordinates: {latitude: 57.149911, longitude: -2.078433}, first: 3) {
    edges {
      node {
        venues(first: 10) {
          edges {
            node {
              events {
                id
              }
            }
          }
        }
      }
    }
  }
}

```

I am expecting all event records to be fetched in the same query, though instead I am getting hundreds of queries fetching 1-10 events per query.

**Comment by leebyron** [comment]
I suggest logging when your upstream promises are being created and when they complete. Sounds like a missed opportunity to batch in a prior set of promises is resulting in those resolving on different ticks and creating separate batches.

**Comment by gajus** [comment]
For others going the perilous ways of debugging a similar issue: if you are using `console.log` to debug the issue then you must pipe the program output in order to ensure that it is non-blocking.

**Comment by sibelius** [comment]
this https://github.com/calebmer/graphql-resolve-batch could help

**Comment by Kosta-Github** [comment]
I like the idea of @bman654:
I am using a pool of `db` connections and would like to collect batches as long as all `db` connections are busy, but as soon as a `db` connection gets released back into the pool the next batched query should/could start; that should be doable by using the `batchSignal: () => waitForSomeSignalToArrive()` approach, right?

**Comment by leebyron** [comment]
Closing this issue since time-based intervals is counter to the goals of DataLoader (to reduce latency and load times), but I would definitely suggest building complimentary packages which have these more specific batching strategies. For example, DataLoader's batching function might itself call to an intermediate API that is more aware of the actual database connection state and able to perform its own delayed batching strategies that are optimized for its specific conditions.
