### ISSUE TITLE
Batching behavior with nested GraphQL resolvers

### ISSUE THREAD

**Issue by SachaG** [facebook/dataloader#79]
Let's say I have a list of the five most recent posts, each of which has one author and five commenters. In GraphQL terms, this means one resolver for `posts`, one for `Post.author`, and one for `Post.commenters`. 

Without batching, loading this list of posts this would result in (1 + 4) database calls to the `users` collection per post, times 5 for a total of 25 database calls (in addition to the initial call to the `posts` collection, of course). 

With perfect batching, you'd expect to only have a single database call to the `users` collection. Right now though, I still have 5 database calls. Is this the intended behavior?

Also, how can I use Dataloader for the initial list of five posts, given that I don't know their ids? Am I supposed to query the database for the five most recent posts first, and then pass their ids on to `loadMany`? (which would presumably result in a second database call to `posts`)?

**Comment by SachaG** [comment]
> Am I supposed to query the database for the five most recent posts first, and then pass their ids on to loadMany? (which would presumably result in a second database call to posts)?

Answering one part of my question: I've since seen `prime`, so I could query the database, and then manually prime the cache with the resulting posts, no need to call `loadMany`.

**Comment by SachaG** [comment]
I think the reason why I'm seeing 5 database calls instead of 1 is that my different resolvers are not all running in the same tick of the event loop. I'm not sure yet how to fix this though…

**Comment by SachaG** [comment]
No, I probably need to brush up on the Node event loop before I can understand what's really going on here. For now I'm happy with the reduction in database calls even if it's not perfect.

**Comment by sibelius** [comment]
@SachaG try this https://github.com/calebmer/graphql-resolve-batch

**Comment by tvildo** [comment]
@SachaG  as you mentioned "perfect batching" is not implemented , dataloader library just schedules every database call  after the current execution context has completed. So if graphql resolvers fire in different eventloop phases you get batched execution in each phase.

**Comment by SachaG** [comment]
Right, I just don't know how to check which calls happen in which eventloop phases and why…

**Comment by sibelius** [comment]
This could help https://dev-blog.apollodata.com/optimizing-your-graphql-request-waterfalls-7c3f3360b051 as well

**Comment by wmertens** [comment]
Had this happen to me, turned out I was storing the dataloader instance on the `context` but the `context` is a shallow copy for each resolver call so instead I created a `context.cache={}` and used that to store instances.

**Comment by leebyron** [comment]
Closing this aging issue, but to summarize:

By using a DataLoader for users (loaded by their ID), we can reduce this into 2 trips to the database.

The first trip is to load the first 5 most recent posts. I presume you already have some way to make this kind of query, as loading lists or searches over lists is outside the domain of Dataloader. I also presume the result of that query contains the information for each of the 5 posts where each post contains ID references for it's author and commenters. (However, if the result was just the IDs of 5 posts to load, DataLoader could help ensure a single request for all 5 posts).

In your GraphQL resolvers for Post.author and Post.commenters, you would use `.load()` on your user DataLoader. Since GraphQL resolves lists in parallel, all 5 posts will have these resolvers called at the same time, thus the DataLoader will collect all requests into a single batched request. 

If "each of which has one author and five commenters." That will result in a single batched database call that will request up to 30 different user IDs. However if the same user appears as an author and commenter, or commenter across many posts, then you may have fewer IDs.

**Comment by SachaG** [comment]
Closing this is fine, as it doesn't really correspond to any specific issue. I guess it's just that even if you understand how Dataloader should work in theory, there can still be implementation details that get in the way of achieving a "perfect score". This is probably just something you have to work out yourself in your own specific code.
