### ISSUE TITLE
How to use when returning entire collection?

### ISSUE THREAD

**Issue by elie222** [facebook/dataloader#88]
Is it possible to use Dataloader when returning an entire collection?

In this case there are no keys. Eg. in mongo it would be `find({})`.

**Comment by luckydrq** [comment]
You can assign a `key` for this case which your server can understand.

**Comment by heuels** [comment]
@elie222 Here is a gist of a DataLoader extension that adds a `loadAll()` method: https://gist.github.com/ryanspradlin/1e951a4dcf737e3fb194

**Comment by allyssonsantos** [comment]
@elie222 did you make dataloader work without keys? I'm having the same problem to make this work...

**Comment by elie222** [comment]
Hi @allyssonsantos. I didn't get it working, but I have time to try either. Let me know if the methods posted by others work for you though

**Comment by ulrikstrid** [comment]
I think you could just load all outside of the loader and then prime the Dataloader with the values.

**Comment by leebyron** [comment]
Dataloader is not really intended for this purpose - it's intended for batching the requests of many individual values. Though a common operation is to prime the cache of a Dataloader after loading many of something - I think the gist posted earlier is a great example of doing that

**Comment by lukejagodzinski** [comment]
@leebyron I think it would be a great idea to add this information to the documentation. I've spent some time trying to understand how it works and I've just understood that as you said DataLoader is intended to fetch individuals documents/values by a key. However, when you're dealing with real-life application there is a temptation to just try fetching multiple values which is wrong.

However, I have the following situation. Let's say you have users and groups that these users belong to. Each user has the `groupId` field. So we have 2 collection `Users` and `Groups`. Now I have the GraphQL query `users(groupId: String!)` which returns all users that belong to the given group. As we can't use data loader directly for that, so we would have to make two queries:

```js
const usersIds = Users.find({groupId: groupId}).map(user => user._id);
userLoader.loadMany(usersIds);
```

So as you can see we could actually not use data loader at all because we're already fetching users belonging to the group but then we lose the ability to reuse already fetched users in some other place of the system in the same query.

From what I understand we should `prime` each value from the first fetch and later we can reuse it. Would be great to have this example in the docs as the `prime` name for the name of the caching function is not intuitive :). At first, I thought that there is no way of doing it.

Until now I can solve it by myself but there is one more thing. In the `userLoader` I'm also checking permissions and I'm not sure if I should do this. What would be the best approach to check permissions when using data loaders?
