### ISSUE TITLE
Pass in debugging/logging context to batchLoaderFn

### ISSUE THREAD

**Issue by hamza-openinvest** [facebook/dataloader#95]
Hi there,

First off, thanks for making and maintaining this library. I'm using dataloader with the `graphql`, `sequelize` and `graphql-sequelize` libraries and can accomplish most of what I need with it with ease.

What I'd like to do is somehow dynamically pass in the request object or logging function to my batchLoadFn (possibly around here: https://github.com/facebook/dataloader/blob/master/src/index.js#L249). The purpose is this: I use middleware to add a unique identifier to the (express) request object, then I log that identifier alongside each executed SQL query in the logs, so I can track all the queries that a single graphql request generates together. This is relatively straightforward to do when `graphql-sequelize` is handling the request, because there's a mechanism for receiving a logging function from the graphql context. However, in some cases I need to do a custom query, wrapped in dataloader. Currently this looks something like this:

```
const myLoader = new DataLoader(async Ids => {
  const queryOptions = { model: MyObj, logging: ??? };
  const myObjs = await sequelize.query(`SELECT .... WHERE Id IN (${Ids.join(',')})`, queryOptions);
  myObjsInOrder = Ids.map( ... ); // some basic logic to put the results in the right order
  return myObjsInOrder; 
});

export new GraphQLObjectType({
  Things: {
    type: someOtherType,
    resolve: myObj => myLoader.load(myObj.Id)
  }
});
```
The above all works great, the only thing I'm missing is being able to pass in a logging function (or logging context object or similar) in the queryOptions, i.e. the `???` is in the example above.

I tried making myLoader a higher order function that returns a loader:
```
    resolve: (myObj, args, ctx) => myLoader(ctx.logging).load(myObj.Id)
```
but that causes multiple DataLoader instances to be created, and therefore no batching occurs (as expected).

Is there a good way to accomplish this? Thanks so much!

**Comment by leebyron** [comment]
I would suggest creating data loaders as part of the context itself, so in your resolver may look like:

```js
resolve: (myObj, args, ctx) => ctx.myLoader.load(myObj.Id)
```

This way you have a unique DataLoader per graphql request/context, which not only scopes it to the express request object as you desire, but also ensures better protection against leaking data between differently logged-in users who may be running queries within the same instance.

Otherwise, with the globally defined DataLoaders you currently have you could actually have *multiple* express request objects responsible for a given batch if your server is responding to multiple requests at the same time.

Closing after answering, but feel free to re-open if you want to continue the conversation.
